- kind: porn
  name: caoliu
  domain: https://cl.vxn75q.info
#  url: https://cl.vxn75q.info/thread0806.php?fid=25&search=hot&page=<page>
  url: https://cl.vxn75q.info/thread0806.php?fid=25&page=<page>
  downloadNumLimit: 1
  downloadSize: 30
  maxPage: 1
  homePrefix: /htm_mob
  heads:
    cookie: ismob=1
    User-Agent: a

